//! The order upstream prints attributes in.
//!
//! Generated by `corpus/attribute-order.nu`, which explains the derivation.
//! In short: an attribute set is held sorted rather than written out as it
//! was read, so `noalias nocapture sret(%T)` comes back
//! `noalias sret(%T) captures(none)`. Two attributes on one declaration say
//! which of them comes first, asked both ways round so that the answer is
//! upstream's order rather than the one the probe happened to write.
//!
//! The quoted attributes are not here. They print after every keyword and
//! sort among themselves by key.
//!
//! Two keywords no declaration can place keep whatever place the sort gave
//! them: upstream allows `elementtype` only on a call site, and `nocapture`
//! never comes back at all, being read as `captures(none)`.

/// Where this attribute sorts, or `usize::MAX` for a keyword nothing
/// measured placed.
pub fn rank(keyword: &str) -> usize {
    ORDER
        .binary_search_by_key(&keyword, |(known, _)| *known)
        .map_or(usize::MAX, |index| ORDER[index].1)
}

/// Sorted by keyword so the lookup is a binary search; the number beside
/// each is its place in the measured order.
static ORDER: &[(&str, usize)] = &[
    ("align", 90),
    ("alignstack", 95),
    ("allocalign", 0),
    ("allockind", 86),
    ("allocptr", 1),
    ("allocsize", 87),
    ("alwaysinline", 2),
    ("builtin", 3),
    ("byref", 81),
    ("byval", 82),
    ("captures", 91),
    ("cold", 4),
    ("convergent", 5),
    ("coro_elide_safe", 7),
    ("coro_only_destroy_when_complete", 6),
    ("dead_on_return", 8),
    ("dead_on_unwind", 9),
    ("dereferenceable", 92),
    ("dereferenceable_or_null", 93),
    ("disable_sanitizer_instrumentation", 10),
    ("elementtype", 11),
    ("fn_ret_thunk_extern", 12),
    ("hot", 13),
    ("hybrid_patchable", 14),
    ("immarg", 15),
    ("inalloca", 83),
    ("initializes", 96),
    ("inlinehint", 16),
    ("inreg", 17),
    ("jumptable", 18),
    ("memory", 88),
    ("minsize", 19),
    ("mustprogress", 20),
    ("naked", 21),
    ("nest", 22),
    ("noalias", 23),
    ("nobuiltin", 24),
    ("nocallback", 25),
    ("nocapture", 26),
    ("nocf_check", 27),
    ("nodivergencesource", 28),
    ("noduplicate", 29),
    ("noext", 30),
    ("nofpclass", 84),
    ("nofree", 31),
    ("noimplicitfloat", 32),
    ("noinline", 33),
    ("nomerge", 34),
    ("nonlazybind", 45),
    ("nonnull", 43),
    ("noprofile", 35),
    ("norecurse", 36),
    ("noredzone", 37),
    ("noreturn", 38),
    ("nosanitize_bounds", 39),
    ("nosanitize_coverage", 40),
    ("nosync", 41),
    ("noundef", 42),
    ("nounwind", 44),
    ("null_pointer_is_valid", 46),
    ("optdebug", 48),
    ("optforfuzzing", 47),
    ("optnone", 49),
    ("optsize", 50),
    ("preallocated", 85),
    ("presplitcoroutine", 51),
    ("range", 97),
    ("readnone", 52),
    ("readonly", 53),
    ("returned", 54),
    ("returns_twice", 55),
    ("safestack", 56),
    ("sanitize_address", 57),
    ("sanitize_hwaddress", 58),
    ("sanitize_memory", 60),
    ("sanitize_memtag", 59),
    ("sanitize_numerical_stability", 61),
    ("sanitize_realtime", 62),
    ("sanitize_realtime_blocking", 63),
    ("sanitize_thread", 64),
    ("sanitize_type", 65),
    ("shadowcallstack", 66),
    ("signext", 67),
    ("skipprofile", 68),
    ("speculatable", 69),
    ("speculative_load_hardening", 70),
    ("sret", 89),
    ("ssp", 71),
    ("sspreq", 72),
    ("sspstrong", 73),
    ("strictfp", 74),
    ("swiftasync", 75),
    ("swifterror", 76),
    ("swiftself", 77),
    ("uwtable", 98),
    ("vscale_range", 99),
    ("willreturn", 78),
    ("writable", 79),
    ("writeonly", 80),
    ("zeroext", 94),
];
