#!/usr/bin/env nu
# Derives the DWARF vocabulary by asking upstream what each number is called.
#
#   nu dwarf-vocabulary.nu [upstream-opt] [out.rs]
#
# A field like `encoding:` takes a word, and a module may write the number
# behind it instead: `encoding: 5` and `encoding: DW_ATE_signed` are the same
# field. Upstream prints the word back, so a printer that keeps the number
# diverges, and a verifier with no list of words cannot say that
# `DW_TAG_badtag` is not one.
#
# The list has been recorded as unobtainable since the sixty-third pass,
# because no specification this project may read enumerates every `DW_TAG_*`.
# But the oracle does: writing `tag: 5` and reading back `DW_TAG_variable` is
# a question `llvm-as` answers, the same way every other rule here is asked.
# So the vocabulary is swept out rather than looked up.
#
# What comes out is `crates/llvm-ir/src/metadata/dwarf.rs`, one table per field, giving
# the word for each number upstream accepts. A number upstream refuses is not
# in the table, which is what makes the table an answer to "is this a word"
# as well as to "what is this number called".

# Each field, where it is written, and the numbers worth asking about. The
# ranges are wide enough to run past the last value each vocabulary defines,
# which is how the sweep knows it has found the end rather than assuming one.
const FIELDS = [
  [name, node, skeleton, ranges];

  # `GenericDINode` takes whatever tag it is given and prints the word when
  # there is one, so it is the probe that sees the whole vocabulary rather
  # than the part one node kind allows.
  ["tag" "GenericDINode" 'header: "h"' [[0 0x1200] [0x4000 0x4200] [0x8000 0x8100] [0x1400 0x1500]]]
  ["encoding" "DIBasicType" 'name: "n", size: 8' [[0 0x100]]]
  ["language" "DICompileUnit" 'file: !2' [[0 0x40] [0x8000 0x8100]]]
  ["emissionKind" "DICompileUnit" 'language: DW_LANG_C99, file: !2' [[0 0x10]]]
  ["nameTableKind" "DICompileUnit" 'language: DW_LANG_C99, file: !2' [[0 0x10]]]
  ["virtuality" "DISubprogram" 'name: "s", scope: null, type: null, spFlags: 0' [[0 0x10]]]
  ["cc" "DISubroutineType" 'types: null' [[0 0x100]]]
  ["checksumkind" "DIFile" 'filename: "f", directory: "d", checksum: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"' [[0 0x10]]]
  ["type" "DIMacro" 'name: "m", value: "v"' [[0 0x10]]]
]

def probe-text [field: string, node: string, skeleton: string, value: int]: nothing -> string {
  let distinct = if $node in ["DICompileUnit" "DISubprogram"] { "distinct " } else { "" }
  let units = if $node == "DICompileUnit" { '!llvm.dbg.cu = !{!0}' } else { '' }
  ([
    '!named = !{!0}'
    $"!0 = ($distinct)!($node)\(($skeleton), ($field): ($value)\)"
    '!2 = !DIFile(filename: "a", directory: "d")'
    $units
    '!llvm.module.flags = !{!9}'
    '!9 = !{i32 2, !"Debug Info Version", i32 3}'
  ] | where $it != "" | str join "\n")
}

def main [upstream_opt: path = "opt", out: path = "dwarf.rs"] {
  let work = (mktemp -d)
  let source = ([$work "probe.ll"] | path join)
  mut tables = []
  for field in $FIELDS {
    mut pairs = []
    for range in $field.ranges {
      for value in ($range.0)..<($range.1) {
        probe-text $field.name $field.node $field.skeleton $value | save -f $source
        let printed = (do { ^$upstream_opt -S $source -o - } | complete)
        if $printed.exit_code != 0 { continue }
        let text = (try { $printed.stdout | decode utf-8 } catch { $printed.stdout })
        let line = ($text | lines | where ($it | str starts-with "!0 = ") | first)
        let word = (
          $line
          | parse --regex $"($field.name): \(?P<word>[A-Za-z_][A-Za-z0-9_]*\)"
          | get word?
          | default []
        )
        if ($word | is-empty) { continue }
        $pairs = ($pairs | append {value: $value, word: ($word | first)})
      }
    }
    print $"($field.name) via ($field.node): ($pairs | length) words"
    $tables = ($tables | append {field: $field.name, pairs: $pairs})
  }
  rm -rf $work

  # A vocabulary swept on more than one node kind is the union: each kind
  # takes the tags that make sense for it, and the words are the same words.
  let tables = (
    $tables
    | group-by field
    | transpose field rows
    | each {|group|
      {
        field: $group.field
        pairs: ($group.rows | get pairs | flatten | uniq-by value | sort-by value)
      }
    }
  )
  let body = (
    $tables
    | each {|table|
      let rows = (
        $table.pairs
        | each {|pair| $"    \(($pair.value), \"($pair.word)\"\)," }
        | str join "\n"
      )
      $"/// The words `($table.field):` takes, and the number behind each.\npub static ($table.field | str upcase): &[\(u64, &str\)] = &[\n($rows)\n];\n"
    }
    | str join "\n"
  )
  let header = "//! The DWARF vocabulary, as upstream spells it.
//!
//! Generated by `corpus/dwarf-vocabulary.nu`, which explains the derivation.
//! In short: a field that takes a word also takes the number behind it, and
//! upstream prints the word back, so the map from one to the other is a
//! question the assembler answers rather than a list to be copied from a
//! specification this project may not read.
//!
//! A number no table here names is one upstream refuses, which makes these
//! tables the answer to \"is this a word\" as well as to \"what is this number
//! called\".

/// The word a number is spelled as, in the vocabulary a field takes.
pub fn word(vocabulary: &[(u64, &'static str)], value: u64) -> Option<&'static str> {
    vocabulary
        .iter()
        .find(|(number, _)| *number == value)
        .map(|(_, word)| *word)
}

/// Whether a word is one this vocabulary has.
pub fn has(vocabulary: &[(u64, &'static str)], word: &str) -> bool {
    vocabulary.iter().any(|(_, known)| *known == word)
}
"
  $"($header)\n($body)" | save -f $out
  print $"wrote ($out)"
}
