#!/usr/bin/env nu
# Generates the intrinsic signature table from LangRef's `declare` lines.
#
#   nu intrinsic-signatures.nu <llvm-source-tree> <out.rs>
#
# LangRef documents each intrinsic with one or more `declare` lines, and an
# overloaded intrinsic gets several: `llvm.cttz.i8` and `llvm.cttz.v2i32` are
# the same intrinsic instantiated twice. Reading all of them together says
# which argument positions vary and which do not, and the ones that do not
# are rules. `llvm.cttz`'s second argument is `i1` in every instantiation, so
# a call passing anything else is calling something that does not exist.
#
# What comes out is deliberately partial. A position whose type varies is
# recorded as unknown rather than guessed, and a type that is not a plain
# integer, pointer, metadata or float is recorded as unknown too, because
# matching those needs more of the type system than a text comparison has.
# The table therefore states the arity of every intrinsic with a fixed one
# and the types it is sure of, which is a smaller claim than upstream makes
# and one this project can back.

# The mangling suffix a call's argument types add: `llvm.smax.v4i32` is
# `llvm.smax`.
def strip-mangling [name: string]: nothing -> string {
  mut parts = ($name | split row ".")
  while (($parts | length) > 2
    and (($parts | last) =~ '^(v[0-9].*|nxv[0-9].*|p[0-9]+|i[0-9]+|f[0-9]+|bf[0-9]+|f80|f128|ppcf128|isVoid|a[0-9].*)$')) {
    $parts = ($parts | drop 1)
  }
  $parts | str join "."
}

# Splits an argument list on the commas that are not inside brackets.
def split-arguments [text: string]: nothing -> list<string> {
  mut out = []
  mut depth = 0
  mut current = ""
  for char in ($text | split chars) {
    # A literal struct is one argument however many commas it holds:
    # `{ i32, ptr addrspace(5), i32, i32 }` was four before the brace was
    # counted.
    if $char in ["<" "(" "[" "{"] { $depth = $depth + 1 }
    if $char in [">" ")" "]" "}"] { $depth = $depth - 1 }
    if $char == "," and $depth == 0 {
      $out = ($out | append ($current | str trim))
      $current = ""
    } else {
      $current = $current + $char
    }
  }
  if ($current | str trim) != "" { $out = ($out | append ($current | str trim)) }
  $out
}

# One argument's type, with its operand name and its attributes removed.
def argument-type [argument: string]: nothing -> string {
  $argument
  | str replace --regex '\s+(<[^<>]*>|%\S+)\s*$' ''
  | str replace --all --regex '\b(immarg|readonly|writeonly|nocapture|noalias|inreg|zeroext|signext|noundef|nonnull|dereferenceable\([0-9]+\)|align [0-9]+|byval\([^)]*\))\b' ''
  | str trim
}

# The Rust spelling of a type we are willing to match, or `Any`.
def rust-parameter [text: string]: nothing -> string {
  if $text =~ '^i[0-9]+$' {
    let bits = ($text | str substring 1..)
    $"Parameter::Int\(($bits)\)"
  } else if $text == "ptr" {
    "Parameter::Pointer"
  } else if $text == "metadata" {
    "Parameter::Metadata"
  } else if $text in ["half" "float" "double"] {
    "Parameter::Float"
  } else {
    "Parameter::Any"
  }
}

def main [tree: path, out: path] {
  let langref = ([$tree "llvm" "docs" "LangRef.rst"] | path join)
  if not ($langref | path exists) {
    error make {msg: $"no LangRef at ($langref)"}
  }

  let declares = (
    open --raw $langref
    | lines
    | each {|line| $line | str trim}
    | where ($it | str starts-with "declare ")
    | parse --regex '^declare\s+(?P<result>.+?)\s+@(?P<name>llvm\.[A-Za-z0-9_.]*[A-Za-z0-9_])\s*\((?P<arguments>.*?)\)\s*(#[0-9]+)?$'
  )

  let rows = (
    $declares
    | each {|row|
      {
        name: (strip-mangling $row.name)
        types: (split-arguments $row.arguments | each {|a| argument-type $a})
      }
    }
    | where not ($it.types | any {|t| $t | str contains "..."})
  )

  mut entries = []
  for group in ($rows | group-by name | transpose name rows) {
    let arities = ($group.rows | each {|r| $r.types | length} | uniq)
    if ($arities | length) != 1 { continue }
    let arity = ($arities | first)
    mut parameters = []
    for index in 0..<$arity {
      let seen = ($group.rows | each {|r| $r.types | get $index} | uniq)
      let text = if ($seen | length) == 1 { $seen | first } else { "" }
      $parameters = ($parameters | append (rust-parameter $text))
    }
    $entries = ($entries | append {name: $group.name, parameters: $parameters})
  }

  let sorted = ($entries | sort-by name)
  let body = (
    $sorted
    | each {|entry|
      let list = ($entry.parameters | str join ", ")
      $"    \(\"($entry.name)\", &[($list)]\),"
    }
    | str join "\n"
  )

  let header = "//! What LangRef says each intrinsic takes.
//!
//! Generated by `corpus/intrinsic-signatures.nu`, which explains the
//! derivation and what it leaves out. In short: LangRef documents an
//! overloaded intrinsic with one `declare` line per instantiation, so a
//! position whose type is the same in all of them is a rule and a position
//! whose type varies is not. Only the arity and the types that are the same
//! everywhere are here, which is a smaller claim than upstream makes.

/// What one argument position has to be.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Parameter {
    /// Overloaded, or a type this table does not try to match.
    Any,
    Int(u32),
    Pointer,
    Metadata,
    Float,
}

/// The signature documented under exactly this name, with no reduction.
pub fn signature_exact(name: &str) -> Option<&'static [Parameter]> {
    let index = SIGNATURES
        .binary_search_by_key(&name, |(name, _)| *name)
        .ok()?;
    Some(SIGNATURES[index].1)
}

/// The signature LangRef documents for this name or for the one it
/// instantiates, or `None` when it documents none or documents inconsistent
/// arities.
///
/// The reduction is `super::candidates`, which drops trailing mangled types
/// and stops at the first component that is a word, so a name cannot reach a
/// shorter one that is merely a prefix of it.
pub fn signature(name: &str) -> Option<&'static [Parameter]> {
    super::candidates(name).find_map(signature_exact)
}

/// Sorted, so the lookup can be a binary search.
static SIGNATURES: &[(&str, &[Parameter])] = &["

  [$header, $body, "];", ""] | str join "\n" | save --force $out
  print $"($declares | length) declare lines, ($sorted | length) intrinsics into ($out)"
}
