#!/usr/bin/env nu
# Generates the table of data layouts a triple implies.
#
#   nu target-data-layouts.nu <llvm-source-tree> <opt> <out.rs>
#
# A module that names a target and writes no data layout gets one anyway:
# upstream fills in the layout that target uses, so
# `target triple = "x86_64-unknown-linux-gnu"` alone comes back carrying
# `target datalayout = "e-m:e-p270:32:32-..."`. Printing no layout where
# upstream prints one is a difference on every such module.
#
# The layout is a property of the target rather than of the IR, which is the
# shape of thing this project measures rather than reasons about. One module
# per triple asks one question: write the triple alone and read back what
# upstream put beside it. A triple it does not recognise comes back with no
# layout at all, and that is recorded as an answer too, because a triple
# whose target upstream has no backend for is one we must also leave alone.
#
# The triples come from upstream's own tests. That is coverage of what
# appears rather than of what could: a triple no test names has no row and
# gets nothing, which is what we did before this table existed. Computing a
# layout from a triple's parts instead would be reimplementing every
# backend, and there is no specification of that outside the backends.

def main [tree: path, opt: path, out: path] {
  let root = ([$tree "llvm" "test"] | path join)
  if not ($root | path exists) {
    error make {msg: $"no test tree at ($root)"}
  }
  let triples = (
    ^grep -rhoE '^target triple = "[^"]*"' --include='*.ll' $root
    | lines
    | uniq
    | each {|line| $line | str replace --regex '^target triple = "' '' | str replace --regex '"$' ''}
    | where ($it | is-not-empty)
    | uniq
    | sort
  )
  print $"($triples | length) distinct triples in llvm/test"

  let work = (mktemp -d)
  let source = ([$work "triple.ll"] | path join)
  mut rows = []
  mut silent = 0
  for triple in $triples {
    $"target triple = \"($triple)\"\n" | save --force $source
    let run = (do { ^$opt -S $source -o - } | complete)
    if $run.exit_code != 0 { continue }
    let found = (
      $run.stdout
      | lines
      | where ($it | str starts-with "target datalayout = ")
      | each {|line| $line | str replace --regex '^target datalayout = "' '' | str replace --regex '"$' ''}
    )
    if ($found | is-empty) {
      # A target upstream has no layout for. Recorded as nothing rather than
      # skipped, so that the table says "asked, and the answer was none".
      $silent = $silent + 1
      continue
    }
    $rows = ($rows | append {triple: $triple, layout: ($found | first)})
  }
  rm -rf $work
  print $"($rows | length) triples imply a layout, ($silent) imply none"

  let distinct = ($rows | get layout | uniq | length)
  print $"($distinct) distinct layouts among them"

  let body = (
    $rows
    | sort-by triple
    | each {|row| $"    \(\"($row.triple)\", \"($row.layout)\"\),"}
    | str join "\n"
  )
  let header = "//! The data layout each target triple implies.
//!
//! Generated by `corpus/target-data-layouts.nu`, which explains the
//! derivation. In short: a module naming a target and writing no data layout
//! gets that target's layout filled in, so printing nothing there is a
//! difference from upstream on every such module. One module per triple asks
//! one question.
//!
//! The triples are the ones upstream's own tests name, which is coverage of
//! what appears rather than of what could. A triple with no row here gets
//! nothing, which is what happened before this table existed. Deriving a
//! layout from a triple's parts instead would be reimplementing every
//! backend, and no specification of that exists outside them.

/// The layout this triple implies, or `None` when nothing measured says.
pub fn layout_for(triple: &str) -> Option<&'static str> {
    let index = LAYOUTS
        .binary_search_by_key(&triple, |(triple, _)| *triple)
        .ok()?;
    Some(LAYOUTS[index].1)
}

/// Sorted, so the lookup can be a binary search.
static LAYOUTS: &[(&str, &str)] = &["

  [$header, $body, "];", ""] | str join "\n" | save --force $out
  ^rustfmt --edition 2021 $out
  print $"written to ($out)"
}
