//! The intrinsics upstream reads at an older arity than they have.
//!
//! Generated by `corpus/intrinsic-arity.nu`, which explains the derivation.
//! In short: a declaration written before an intrinsic gained a parameter is
//! upgraded rather than refused, so writing one out and reading back the call
//! says what the added arguments are.
//!
//! This is what upstream's own tests write, the way the rename table is: the
//! old spellings live there because that is what those tests test, and no
//! specification enumerates the arities that used to exist.

/// One upgrade: the base name, the arity it was written at, and the arguments
/// upstream appends to a call, written the way it writes them.
type Entry = (&'static str, u8, &'static [&'static str]);

/// What a call to this name at this arity gains, or `None` when nothing
/// measured says it gains anything.
/// Both sides are reduced to the base name, so a width no test happens to
/// declare is upgraded the way the ones they do declare are. Every row of one
/// base agrees about what it gains, which is what makes that sound: the rows
/// are per instantiation because the sweep asks about a declaration as
/// written, not because an instantiation could differ.
pub fn upgrade(name: &str, arity: usize) -> Option<&'static [&'static str]> {
    let arity = u8::try_from(arity).ok()?;
    let base = super::base_name(name);
    UPGRADES
        .iter()
        .find(|(known, at, _)| *at == arity && super::base_name(known) == base)
        .map(|(_, _, added)| *added)
}

/// Whether upstream drops this intrinsic entirely, its calls with it.
pub fn is_dropped(name: &str) -> bool {
    let base = super::base_name(name);
    DROPPED.iter().any(|known| super::base_name(known) == base)
}

/// Sorted by name and then by the arity written.
static UPGRADES: &[Entry] = &[
    ("llvm.coro.end", 2, &["token none"]),
    ("llvm.ctlz.i11", 1, &["i1 false"]),
    ("llvm.ctlz.i16", 1, &["i1 false"]),
    ("llvm.ctlz.i32", 1, &["i1 false"]),
    ("llvm.ctlz.i64", 1, &["i1 false"]),
    ("llvm.ctlz.i73", 1, &["i1 false"]),
    ("llvm.ctlz.i8", 1, &["i1 false"]),
    ("llvm.ctlz.nxv16i1", 1, &["i1 false"]),
    ("llvm.ctlz.nxv16i8", 1, &["i1 false"]),
    ("llvm.ctlz.nxv2i1", 1, &["i1 false"]),
    ("llvm.ctlz.nxv2i64", 1, &["i1 false"]),
    ("llvm.ctlz.nxv4i1", 1, &["i1 false"]),
    ("llvm.ctlz.nxv4i32", 1, &["i1 false"]),
    ("llvm.ctlz.nxv8i1", 1, &["i1 false"]),
    ("llvm.ctlz.nxv8i16", 1, &["i1 false"]),
    ("llvm.ctlz.v128i16", 1, &["i1 false"]),
    ("llvm.ctlz.v128i8", 1, &["i1 false"]),
    ("llvm.ctlz.v16i16", 1, &["i1 false"]),
    ("llvm.ctlz.v16i32", 1, &["i1 false"]),
    ("llvm.ctlz.v16i64", 1, &["i1 false"]),
    ("llvm.ctlz.v16i8", 1, &["i1 false"]),
    ("llvm.ctlz.v1i64", 1, &["i1 false"]),
    ("llvm.ctlz.v256i8", 1, &["i1 false"]),
    ("llvm.ctlz.v2i13", 1, &["i1 false"]),
    ("llvm.ctlz.v2i16", 1, &["i1 false"]),
    ("llvm.ctlz.v2i32", 1, &["i1 false"]),
    ("llvm.ctlz.v2i64", 1, &["i1 false"]),
    ("llvm.ctlz.v32i16", 1, &["i1 false"]),
    ("llvm.ctlz.v32i32", 1, &["i1 false"]),
    ("llvm.ctlz.v32i64", 1, &["i1 false"]),
    ("llvm.ctlz.v32i8", 1, &["i1 false"]),
    ("llvm.ctlz.v4i16", 1, &["i1 false"]),
    ("llvm.ctlz.v4i32", 1, &["i1 false"]),
    ("llvm.ctlz.v4i64", 1, &["i1 false"]),
    ("llvm.ctlz.v4i8", 1, &["i1 false"]),
    ("llvm.ctlz.v64i16", 1, &["i1 false"]),
    ("llvm.ctlz.v64i32", 1, &["i1 false"]),
    ("llvm.ctlz.v64i8", 1, &["i1 false"]),
    ("llvm.ctlz.v8i16", 1, &["i1 false"]),
    ("llvm.ctlz.v8i32", 1, &["i1 false"]),
    ("llvm.ctlz.v8i64", 1, &["i1 false"]),
    ("llvm.ctlz.v8i8", 1, &["i1 false"]),
    ("llvm.cttz.i11", 1, &["i1 false"]),
    ("llvm.cttz.i128", 1, &["i1 false"]),
    ("llvm.cttz.i16", 1, &["i1 false"]),
    ("llvm.cttz.i32", 1, &["i1 false"]),
    ("llvm.cttz.i64", 1, &["i1 false"]),
    ("llvm.cttz.i73", 1, &["i1 false"]),
    ("llvm.cttz.i8", 1, &["i1 false"]),
    ("llvm.cttz.nxv16i1", 1, &["i1 false"]),
    ("llvm.cttz.nxv16i8", 1, &["i1 false"]),
    ("llvm.cttz.nxv2i1", 1, &["i1 false"]),
    ("llvm.cttz.nxv2i64", 1, &["i1 false"]),
    ("llvm.cttz.nxv4i1", 1, &["i1 false"]),
    ("llvm.cttz.nxv4i32", 1, &["i1 false"]),
    ("llvm.cttz.nxv8i1", 1, &["i1 false"]),
    ("llvm.cttz.nxv8i16", 1, &["i1 false"]),
    ("llvm.cttz.v128i16", 1, &["i1 false"]),
    ("llvm.cttz.v128i8", 1, &["i1 false"]),
    ("llvm.cttz.v16i16", 1, &["i1 false"]),
    ("llvm.cttz.v16i32", 1, &["i1 false"]),
    ("llvm.cttz.v16i64", 1, &["i1 false"]),
    ("llvm.cttz.v16i8", 1, &["i1 false"]),
    ("llvm.cttz.v1i64", 1, &["i1 false"]),
    ("llvm.cttz.v256i8", 1, &["i1 false"]),
    ("llvm.cttz.v2i13", 1, &["i1 false"]),
    ("llvm.cttz.v2i16", 1, &["i1 false"]),
    ("llvm.cttz.v2i32", 1, &["i1 false"]),
    ("llvm.cttz.v2i64", 1, &["i1 false"]),
    ("llvm.cttz.v32i16", 1, &["i1 false"]),
    ("llvm.cttz.v32i32", 1, &["i1 false"]),
    ("llvm.cttz.v32i64", 1, &["i1 false"]),
    ("llvm.cttz.v32i8", 1, &["i1 false"]),
    ("llvm.cttz.v4i16", 1, &["i1 false"]),
    ("llvm.cttz.v4i32", 1, &["i1 false"]),
    ("llvm.cttz.v4i64", 1, &["i1 false"]),
    ("llvm.cttz.v4i8", 1, &["i1 false"]),
    ("llvm.cttz.v64i16", 1, &["i1 false"]),
    ("llvm.cttz.v64i32", 1, &["i1 false"]),
    ("llvm.cttz.v64i8", 1, &["i1 false"]),
    ("llvm.cttz.v8i16", 1, &["i1 false"]),
    ("llvm.cttz.v8i32", 1, &["i1 false"]),
    ("llvm.cttz.v8i64", 1, &["i1 false"]),
    ("llvm.cttz.v8i8", 1, &["i1 false"]),
    ("llvm.objectsize.i16.p3", 2, &["i1 false", "i1 false"]),
    ("llvm.objectsize.i32", 2, &["i1 false", "i1 false"]),
    ("llvm.objectsize.i32.p0", 2, &["i1 false", "i1 false"]),
    ("llvm.objectsize.i32.p1", 2, &["i1 false", "i1 false"]),
    ("llvm.objectsize.i32.p2", 2, &["i1 false", "i1 false"]),
    ("llvm.objectsize.i32.p3", 2, &["i1 false", "i1 false"]),
    ("llvm.objectsize.i64", 2, &["i1 false", "i1 false"]),
    ("llvm.objectsize.i64.p0", 2, &["i1 false", "i1 false"]),
];

/// Sorted, so the lookup can be a binary search.
static DROPPED: &[&str] = &[
    "llvm.dbg.addr",
    "llvm.dbg.assign",
    "llvm.dbg.declare",
    "llvm.dbg.label",
    "llvm.dbg.value",
    "llvm.stackprotectorcheck",
];
