//! What attributes upstream gives each intrinsic.
//!
//! Generated by `corpus/intrinsic-attributes.nu`, which explains the
//! derivation. In short: upstream replaces whatever attributes an intrinsic
//! declaration was written with by the intrinsic's own, so writing out each
//! `declare` line LangRef documents and reading it back through
//! `llvm-as | llvm-dis` says what they are. LangRef supplies the signature,
//! which has to be right for the name to be recognised at all; it does not
//! supply the attributes and does not have to.
//!
//! The text is what upstream prints, and is read back through the same
//! attribute parser a module's own attributes go through, so the two cannot
//! drift apart.

/// The attributes one intrinsic carries.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Attributes {
    /// What goes in the function's attribute group, in upstream's order.
    pub function: &'static str,
    /// What goes before the return type, empty when nothing does.
    pub ret: &'static str,
    /// One entry per parameter, in order, empty where that parameter
    /// carries nothing.
    pub params: &'static [&'static str],
}

/// What upstream gives the intrinsic this name instantiates, or `None` when
/// it is not one whose attributes were measured.
pub fn attributes(name: &str) -> Option<&'static Attributes> {
    let mut candidate = name;
    loop {
        if let Ok(index) = ATTRIBUTES.binary_search_by_key(&candidate, |(name, _)| *name) {
            return Some(&ATTRIBUTES[index].1);
        }
        match candidate.rsplit_once('.') {
            Some((rest, _)) if rest.matches('.').count() >= 1 => candidate = rest,
            _ => return None,
        }
    }
}

/// Sorted, so the lookup can be a binary search.
static ATTRIBUTES: &[(&str, Attributes)] = &[
    (
        "llvm.abs",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "immarg"],
        },
    ),
    (
        "llvm.acos",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.addressofreturnaddress",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.adjust.trampoline",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: read)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.allow.runtime.check",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "noundef",
            params: &[""],
        },
    ),
    (
        "llvm.allow.ubsan.check",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "noundef",
            params: &["immarg"],
        },
    ),
    (
        "llvm.annotation",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.arithmetic.fence",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.asin",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.assume",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)",
            ret: "",
            params: &["noundef"],
        },
    ),
    (
        "llvm.atan",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.atan2",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.bitreverse",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.bswap",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.call.preallocated.arg",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.call.preallocated.setup",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.canonicalize",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.ceil",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.clear_cache",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.codeview.annotation",
        Attributes {
            function: "nocallback noduplicate nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.convert.from.fp16",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.convert.to.fp16",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.copysign",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.cos",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.cosh",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.ctlz",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "immarg"],
        },
    ),
    (
        "llvm.ctpop",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.cttz",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "immarg"],
        },
    ),
    (
        "llvm.debugtrap",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.donothing",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.exp",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.exp10",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.exp2",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.expect",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.expect.with.probability",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.experimental.constrained.acos",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.asin",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.atan",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.atan2",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.ceil",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.cos",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.cosh",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.exp",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.exp2",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fadd",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fdiv",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.floor",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fma",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fmul",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fmuladd",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fpext",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fptosi",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fptoui",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fptrunc",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.frem",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.fsub",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.llrint",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.llround",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.log",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.log10",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.log2",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.lrint",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.lround",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.nearbyint",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.pow",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.powi",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.rint",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.round",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.roundeven",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.sin",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.sinh",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.sitofp",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.sqrt",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.tan",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.tanh",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.constrained.trunc",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.constrained.uitofp",
        Attributes {
            function: "nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.cttz.elts",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "immarg"],
        },
    ),
    (
        "llvm.experimental.gc.relocate",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "immarg", "immarg"],
        },
    ),
    (
        "llvm.experimental.get.vector.length",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "immarg", "immarg"],
        },
    ),
    (
        "llvm.experimental.memset.pattern",
        Attributes {
            function: "nocallback nofree nounwind willreturn memory(argmem: write)",
            ret: "",
            params: &["writeonly captures(none)", "", "", "immarg"],
        },
    ),
    (
        "llvm.experimental.vector.compress",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.vector.extract.last.active",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.vector.histogram.add",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.vector.histogram.uadd.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.vector.histogram.umax",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.vector.histogram.umin",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.vector.partial.reduce.add",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.experimental.vp.reverse",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.vp.splat",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.experimental.vp.splice",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg", "", "", ""],
        },
    ),
    (
        "llvm.experimental.vp.strided.load",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: read)",
            ret: "",
            params: &["captures(none)", "", "", ""],
        },
    ),
    (
        "llvm.experimental.vp.strided.store",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: write)",
            ret: "",
            params: &["", "captures(none)", "", "", ""],
        },
    ),
    (
        "llvm.experimental.widenable.condition",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(inaccessiblemem: readwrite)",
            ret: "noundef",
            params: &[],
        },
    ),
    (
        "llvm.fabs",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.fake.use",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.floor",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.fma",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.fmuladd",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.fptosi.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.fptoui.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.fptrunc.round",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.frameaddress",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["immarg"],
        },
    ),
    (
        "llvm.frexp",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.fshl",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.fshr",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.gcread",
        Attributes {
            function: "nounwind memory(argmem: read)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.gcroot",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.gcwrite",
        Attributes {
            function: "nounwind memory(argmem: readwrite)",
            ret: "",
            params: &["", "captures(none)", "captures(none)"],
        },
    ),
    (
        "llvm.get.active.lane.mask",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.get.dynamic.area.offset",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.get.fpenv",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.get.fpmode",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.get.rounding",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.init.trampoline",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["writeonly captures(none)", "readnone", "readnone"],
        },
    ),
    (
        "llvm.instrprof.value.profile",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.invariant.end",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["", "immarg", "captures(none)"],
        },
    ),
    (
        "llvm.invariant.start",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["immarg", "captures(none)"],
        },
    ),
    (
        "llvm.is.constant",
        Attributes {
            function: "convergent nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.is.fpclass",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "immarg"],
        },
    ),
    (
        "llvm.launder.invariant.group",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.ldexp",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.lifetime.end",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["immarg", "captures(none)"],
        },
    ),
    (
        "llvm.lifetime.start",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &["immarg", "captures(none)"],
        },
    ),
    (
        "llvm.llrint",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.llround",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.localescape",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.localrecover",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.log",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.log10",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.log2",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.loop.decrement",
        Attributes {
            function: "nocallback noduplicate nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.loop.decrement.reg",
        Attributes {
            function: "nocallback noduplicate nofree nosync nounwind willreturn",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.lrint",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.lround",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.masked.compressstore",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: write)",
            ret: "",
            params: &["", "captures(none)", ""],
        },
    ),
    (
        "llvm.masked.expandload",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(read)",
            ret: "",
            params: &["captures(none)", "", ""],
        },
    ),
    (
        "llvm.masked.gather",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(read)",
            ret: "",
            params: &["", "immarg", "", ""],
        },
    ),
    (
        "llvm.masked.load",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: read)",
            ret: "",
            params: &["captures(none)", "immarg", "", ""],
        },
    ),
    (
        "llvm.masked.scatter",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(write)",
            ret: "",
            params: &["", "", "immarg", ""],
        },
    ),
    (
        "llvm.masked.store",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: write)",
            ret: "",
            params: &["", "captures(none)", "immarg", ""],
        },
    ),
    (
        "llvm.maximum",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.maximumnum",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.maxnum",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.memcpy",
        Attributes {
            function: "nocallback nofree nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &[
                "noalias writeonly captures(none)",
                "noalias readonly captures(none)",
                "",
                "immarg",
            ],
        },
    ),
    (
        "llvm.memcpy.element.unordered.atomic",
        Attributes {
            function: "nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &[
                "writeonly captures(none)",
                "readonly captures(none)",
                "",
                "immarg",
            ],
        },
    ),
    (
        "llvm.memcpy.inline",
        Attributes {
            function: "nocallback nofree nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &[
                "noalias writeonly captures(none)",
                "noalias readonly captures(none)",
                "",
                "immarg",
            ],
        },
    ),
    (
        "llvm.memmove",
        Attributes {
            function: "nocallback nofree nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &[
                "writeonly captures(none)",
                "readonly captures(none)",
                "",
                "immarg",
            ],
        },
    ),
    (
        "llvm.memmove.element.unordered.atomic",
        Attributes {
            function: "nosync nounwind willreturn memory(argmem: readwrite)",
            ret: "",
            params: &[
                "writeonly captures(none)",
                "readonly captures(none)",
                "",
                "immarg",
            ],
        },
    ),
    (
        "llvm.memset",
        Attributes {
            function: "nocallback nofree nounwind willreturn memory(argmem: write)",
            ret: "",
            params: &["writeonly captures(none)", "", "", "immarg"],
        },
    ),
    (
        "llvm.memset.element.unordered.atomic",
        Attributes {
            function: "nosync nounwind willreturn memory(argmem: write)",
            ret: "",
            params: &["writeonly captures(none)", "", "", "immarg"],
        },
    ),
    (
        "llvm.memset.inline",
        Attributes {
            function: "nocallback nofree nounwind willreturn memory(argmem: write)",
            ret: "",
            params: &["writeonly captures(none)", "", "", "immarg"],
        },
    ),
    (
        "llvm.minimum",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.minimumnum",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.minnum",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.modf",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.nearbyint",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.objc.autorelease",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["returned"],
        },
    ),
    (
        "llvm.objc.autoreleasePoolPop",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.objc.autoreleasePoolPush",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.objc.autoreleaseReturnValue",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["returned"],
        },
    ),
    (
        "llvm.objc.copyWeak",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.objc.destroyWeak",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.objc.initWeak",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.objc.loadWeak",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.objc.loadWeakRetained",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.objc.moveWeak",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.objc.release",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.objc.retain",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["returned"],
        },
    ),
    (
        "llvm.objc.retainAutorelease",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["returned"],
        },
    ),
    (
        "llvm.objc.retainAutoreleaseReturnValue",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["returned"],
        },
    ),
    (
        "llvm.objc.retainAutoreleasedReturnValue",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.objc.retainBlock",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.objc.storeStrong",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.objc.storeWeak",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.objectsize",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "immarg", "immarg", "immarg"],
        },
    ),
    (
        "llvm.pcmarker",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.pow",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.powi",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.prefetch",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: readwrite, inaccessiblemem: readwrite)",
            ret: "",
            params: &["readonly captures(none)", "immarg", "immarg", "immarg"],
        },
    ),
    (
        "llvm.ptr.annotation",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.read_register",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(read)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.read_volatile_register",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.readcyclecounter",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.readsteadycounter",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.reset.fpenv",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.reset.fpmode",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.returnaddress",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["immarg"],
        },
    ),
    (
        "llvm.rint",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.round",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.roundeven",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.sadd.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.sadd.with.overflow",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.sdiv.fix",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.sdiv.fix.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.seh.scope.begin",
        Attributes {
            function: "nounwind memory(none)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.seh.scope.end",
        Attributes {
            function: "nounwind memory(none)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.seh.try.begin",
        Attributes {
            function: "nounwind willreturn memory(write)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.seh.try.end",
        Attributes {
            function: "nounwind willreturn memory(write)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.set.fpenv",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.set.fpmode",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.set.loop.iterations",
        Attributes {
            function: "nocallback noduplicate nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.set.rounding",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.sideeffect",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.sin",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.sincos",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.sincospi",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.sinh",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.smax",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.smin",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.smul.fix",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.smul.fix.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.smul.with.overflow",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.sponentry",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.sqrt",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.sshl.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.ssub.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.ssub.with.overflow",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.stackguard",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.stackprotector",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.stackrestore",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.stacksave",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.start.loop.iterations",
        Attributes {
            function: "nocallback noduplicate nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.stepvector",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.strip.invariant.group",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.swift.async.context.addr",
        Attributes {
            function: "nounwind",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.tan",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.tanh",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.test.set.loop.iterations",
        Attributes {
            function: "nocallback noduplicate nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.test.start.loop.iterations",
        Attributes {
            function: "nocallback noduplicate nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.thread.pointer",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.threadlocal.address",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "nonnull",
            params: &["nonnull"],
        },
    ),
    (
        "llvm.trap",
        Attributes {
            function: "cold noreturn nounwind memory(inaccessiblemem: write)",
            ret: "",
            params: &[],
        },
    ),
    (
        "llvm.trunc",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.type.checked.load",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.type.checked.load.relative",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.type.test",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.uadd.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.uadd.with.overflow",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.ubsantrap",
        Attributes {
            function: "cold noreturn nounwind",
            ret: "",
            params: &["immarg"],
        },
    ),
    (
        "llvm.udiv.fix",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.udiv.fix.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.umax",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.umin",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.umul.fix",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.umul.fix.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.umul.with.overflow",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.ushl.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.usub.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.usub.with.overflow",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.va_copy",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.va_end",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.va_start",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.var.annotation",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.vector.deinterleave2",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.deinterleave5",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.deinterleave7",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.extract",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "immarg"],
        },
    ),
    (
        "llvm.vector.insert",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.vector.interleave2",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.vector.interleave3",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vector.interleave5",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.vector.interleave7",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", "", "", "", ""],
        },
    ),
    (
        "llvm.vector.reduce.add",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.and",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.fadd",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.vector.reduce.fmax",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.fmaximum",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.fmin",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.fminimum",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.fmul",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", ""],
        },
    ),
    (
        "llvm.vector.reduce.mul",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.or",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.smax",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.smin",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.umax",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.umin",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reduce.xor",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.reverse",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &[""],
        },
    ),
    (
        "llvm.vector.splice",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "immarg"],
        },
    ),
    (
        "llvm.vp.abs",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.add",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.and",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.ashr",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.bitreverse",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.bswap",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.ceil",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.copysign",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.ctlz",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "immarg", "", ""],
        },
    ),
    (
        "llvm.vp.ctpop",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.cttz",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "immarg", "", ""],
        },
    ),
    (
        "llvm.vp.cttz.elts",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "immarg", "", ""],
        },
    ),
    (
        "llvm.vp.fabs",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.fadd",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.fcmp",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.vp.fdiv",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.floor",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.fma",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.vp.fmul",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.fmuladd",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.vp.fneg",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.fpext",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.fptosi",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.fptoui",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.fptrunc",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.frem",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.fshl",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.vp.fshr",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.vp.fsub",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.gather",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(read)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.icmp",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", "", ""],
        },
    ),
    (
        "llvm.vp.inttoptr",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.is.fpclass",
        Attributes {
            function: "nocallback nofree nosync nounwind speculatable willreturn memory(none)",
            ret: "",
            params: &["", "immarg", "", ""],
        },
    ),
    (
        "llvm.vp.llrint",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.load",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: read)",
            ret: "",
            params: &["captures(none)", "", ""],
        },
    ),
    (
        "llvm.vp.lrint",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.lshr",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.maximum",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.maxnum",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.merge",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.minimum",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.minnum",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.mul",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.nearbyint",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.or",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.ptrtoint",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.add",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.and",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.fadd",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.fmax",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.fmaximum",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.fmin",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.fminimum",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.fmul",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.mul",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.or",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.smax",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.smin",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.umax",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.umin",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.reduce.xor",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.rint",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.round",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.roundeven",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.roundtozero",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.sadd.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.scatter",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.sdiv",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.select",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.sext",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.shl",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.sitofp",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.smax",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.smin",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.sqrt",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.srem",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.ssub.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.store",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(argmem: write)",
            ret: "",
            params: &["", "captures(none)", "", ""],
        },
    ),
    (
        "llvm.vp.sub",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.trunc",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.uadd.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.udiv",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.uitofp",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
    (
        "llvm.vp.umax",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.umin",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.urem",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.usub.sat",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.xor",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", "", ""],
        },
    ),
    (
        "llvm.vp.zext",
        Attributes {
            function: "nocallback nofree nosync nounwind willreturn memory(none)",
            ret: "",
            params: &["", "", ""],
        },
    ),
];
