//! The intrinsics that need a funclet token inside a funclet.
//!
//! Generated by `corpus/intrinsic-funclet.nu`, which explains the derivation.
//! In short: Windows exception handling puts a call inside a funclet, and a
//! call upstream may lower into a real function call has to say which funclet
//! it is in. Upstream refuses one that does not, and which intrinsics those
//! are is measured by asking each one twice, with a bundle and without.
//!
//! An ordinary call needs no bundle there and neither do most intrinsics, so
//! a name with no row here is one that may be called plainly.

/// Whether a call to this name inside a funclet needs a `funclet` bundle.
pub fn needs_funclet_token(name: &str) -> bool {
    let base = super::base_name(name);
    NEEDS.iter().any(|known| super::base_name(known) == base)
}

/// Sorted, so a reader can find a name in it.
static NEEDS: &[&str] = &[
    "llvm.objc.autorelease",
    "llvm.objc.autoreleasePoolPop",
    "llvm.objc.autoreleasePoolPush",
    "llvm.objc.autoreleaseReturnValue",
    "llvm.objc.copyWeak",
    "llvm.objc.destroyWeak",
    "llvm.objc.initWeak",
    "llvm.objc.loadWeak",
    "llvm.objc.loadWeakRetained",
    "llvm.objc.moveWeak",
    "llvm.objc.release",
    "llvm.objc.retain",
    "llvm.objc.retain.autorelease",
    "llvm.objc.retainAutorelease",
    "llvm.objc.retainAutoreleaseReturnValue",
    "llvm.objc.retainAutoreleasedReturnValue",
    "llvm.objc.retainBlock",
    "llvm.objc.retainedObject",
    "llvm.objc.storeStrong",
    "llvm.objc.storeWeak",
    "llvm.objc.sync.enter",
    "llvm.objc.sync.exit",
    "llvm.objc.unretainedObject",
    "llvm.objc.unretainedPointer",
    "llvm.objc.unsafeClaimAutoreleasedReturnValue",
];
