//! The intrinsics upstream renames as it reads them.
//!
//! Generated by `corpus/intrinsic-renames.nu`, which explains the
//! derivation. Some intrinsics are read under one name and written under
//! another: `llvm.wasm.laneselect` comes back
//! `llvm.wasm.relaxed.laneselect`, an older spelling upgraded to the current
//! one, and the call sites come with it.
//!
//! This is not the mangling suffix, which `super::mangling` measures. The
//! name itself is different, so the two are asked separately and the rename
//! is applied first: what a renamed intrinsic is called decides what its
//! components hang off.

/// The name upstream reads this one as, if it reads it as another.
pub fn renamed(name: &str) -> Option<&'static str> {
    let index = RENAMES
        .binary_search_by_key(&name, |(from, _)| *from)
        .ok()?;
    Some(RENAMES[index].1)
}

/// Sorted, so the lookup can be a binary search.
static RENAMES: &[(&str, &str)] = &[
    ("llvm.aarch64.ldaxr.p0i32", "llvm.aarch64.ldaxr"),
    ("llvm.aarch64.ldxr.p0i32", "llvm.aarch64.ldxr"),
    ("llvm.aarch64.neon.addp", "llvm.aarch64.neon.faddp"),
    ("llvm.aarch64.neon.frintn", "llvm.roundeven"),
    ("llvm.aarch64.neon.rbit", "llvm.bitreverse"),
    ("llvm.aarch64.rbit", "llvm.bitreverse"),
    ("llvm.aarch64.stlxr.p0i32", "llvm.aarch64.stlxr"),
    ("llvm.aarch64.stxr.p0i32", "llvm.aarch64.stxr"),
    ("llvm.aarch64.sve.addqv", "llvm.aarch64.sve.faddqv"),
    ("llvm.aarch64.sve.bdep.x.nx16i8", "llvm.aarch64.sve.bdep.x"),
    ("llvm.aarch64.sve.bdep.x.nx2i64", "llvm.aarch64.sve.bdep.x"),
    ("llvm.aarch64.sve.bdep.x.nx4i32", "llvm.aarch64.sve.bdep.x"),
    ("llvm.aarch64.sve.bdep.x.nx8i16", "llvm.aarch64.sve.bdep.x"),
    ("llvm.aarch64.sve.bext.x.nx16i8", "llvm.aarch64.sve.bext.x"),
    ("llvm.aarch64.sve.bext.x.nx2i64", "llvm.aarch64.sve.bext.x"),
    ("llvm.aarch64.sve.bext.x.nx4i32", "llvm.aarch64.sve.bext.x"),
    ("llvm.aarch64.sve.bext.x.nx8i16", "llvm.aarch64.sve.bext.x"),
    (
        "llvm.aarch64.sve.bfdot.lane",
        "llvm.aarch64.sve.bfdot.lane.v2",
    ),
    (
        "llvm.aarch64.sve.bfmlalb.lane",
        "llvm.aarch64.sve.bfmlalb.lane.v2",
    ),
    (
        "llvm.aarch64.sve.bfmlalt.lane",
        "llvm.aarch64.sve.bfmlalt.lane.v2",
    ),
    ("llvm.aarch64.sve.bgrp.x.nx16i8", "llvm.aarch64.sve.bgrp.x"),
    ("llvm.aarch64.sve.bgrp.x.nx2i64", "llvm.aarch64.sve.bgrp.x"),
    ("llvm.aarch64.sve.bgrp.x.nx4i32", "llvm.aarch64.sve.bgrp.x"),
    ("llvm.aarch64.sve.bgrp.x.nx8i16", "llvm.aarch64.sve.bgrp.x"),
    ("llvm.aarch64.sve.ld2", "llvm.aarch64.sve.ld2.sret"),
    (
        "llvm.aarch64.sve.ld2.nxv32i8.nxv16i1.p0i8",
        "llvm.aarch64.sve.ld2.sret",
    ),
    (
        "llvm.aarch64.sve.ld3.nxv48i8.nxv16i1.p0i8",
        "llvm.aarch64.sve.ld3.sret",
    ),
    (
        "llvm.aarch64.sve.ld4.nxv64i8.nxv16i1.p0i8",
        "llvm.aarch64.sve.ld4.sret",
    ),
    (
        "llvm.aarch64.sve.ldnt1.gather.scalar.offset.nxv416",
        "llvm.aarch64.sve.ldnt1.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfb.gather.index.nx2vi64",
        "llvm.aarch64.sve.prfb.gather.index",
    ),
    (
        "llvm.aarch64.sve.prfb.gather.scalar.offset.nx2vi64",
        "llvm.aarch64.sve.prfb.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfb.gather.scalar.offset.nx4vi32",
        "llvm.aarch64.sve.prfb.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfb.gather.sxtw.index.nx2vi64",
        "llvm.aarch64.sve.prfb.gather.sxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfb.gather.sxtw.index.nx4vi32",
        "llvm.aarch64.sve.prfb.gather.sxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfb.gather.uxtw.index.nx2vi64",
        "llvm.aarch64.sve.prfb.gather.uxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfb.gather.uxtw.index.nx4vi32",
        "llvm.aarch64.sve.prfb.gather.uxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfd.gather.index.nx2vi64",
        "llvm.aarch64.sve.prfd.gather.index",
    ),
    (
        "llvm.aarch64.sve.prfd.gather.scalar.offset.nx2vi64",
        "llvm.aarch64.sve.prfd.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfd.gather.scalar.offset.nx4vi32",
        "llvm.aarch64.sve.prfd.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfd.gather.sxtw.index.nx2vi64",
        "llvm.aarch64.sve.prfd.gather.sxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfd.gather.sxtw.index.nx4vi32",
        "llvm.aarch64.sve.prfd.gather.sxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfd.gather.uxtw.index.nx2vi64",
        "llvm.aarch64.sve.prfd.gather.uxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfd.gather.uxtw.index.nx4vi32",
        "llvm.aarch64.sve.prfd.gather.uxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfh.gather.index.nx2vi64",
        "llvm.aarch64.sve.prfh.gather.index",
    ),
    (
        "llvm.aarch64.sve.prfh.gather.scalar.offset.nx2vi64",
        "llvm.aarch64.sve.prfh.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfh.gather.scalar.offset.nx4vi32",
        "llvm.aarch64.sve.prfh.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfh.gather.sxtw.index.nx2vi64",
        "llvm.aarch64.sve.prfh.gather.sxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfh.gather.sxtw.index.nx4vi32",
        "llvm.aarch64.sve.prfh.gather.sxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfh.gather.uxtw.index.nx2vi64",
        "llvm.aarch64.sve.prfh.gather.uxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfh.gather.uxtw.index.nx4vi32",
        "llvm.aarch64.sve.prfh.gather.uxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfw.gather.index.nx2vi64",
        "llvm.aarch64.sve.prfw.gather.index",
    ),
    (
        "llvm.aarch64.sve.prfw.gather.scalar.offset.nx2vi64",
        "llvm.aarch64.sve.prfw.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfw.gather.scalar.offset.nx4vi32",
        "llvm.aarch64.sve.prfw.gather.scalar.offset",
    ),
    (
        "llvm.aarch64.sve.prfw.gather.sxtw.index.nx2vi64",
        "llvm.aarch64.sve.prfw.gather.sxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfw.gather.sxtw.index.nx4vi32",
        "llvm.aarch64.sve.prfw.gather.sxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfw.gather.uxtw.index.nx2vi64",
        "llvm.aarch64.sve.prfw.gather.uxtw.index",
    ),
    (
        "llvm.aarch64.sve.prfw.gather.uxtw.index.nx4vi32",
        "llvm.aarch64.sve.prfw.gather.uxtw.index",
    ),
    ("llvm.aarch64.sve.tuple.create2", "llvm.vector.insert"),
    ("llvm.aarch64.sve.tuple.create3", "llvm.vector.insert"),
    ("llvm.aarch64.sve.tuple.create4", "llvm.vector.insert"),
    ("llvm.aarch64.sve.tuple.get", "llvm.vector.extract"),
    ("llvm.aarch64.sve.tuple.set", "llvm.vector.insert"),
    (
        "llvm.aarch64.sve.whilerw.b.nx16i1",
        "llvm.aarch64.sve.whilerw.b",
    ),
    (
        "llvm.aarch64.sve.whilerw.d.nx2i1",
        "llvm.aarch64.sve.whilerw.d",
    ),
    (
        "llvm.aarch64.sve.whilerw.h.nx8i1",
        "llvm.aarch64.sve.whilerw.h",
    ),
    (
        "llvm.aarch64.sve.whilerw.s.nx4i1",
        "llvm.aarch64.sve.whilerw.s",
    ),
    (
        "llvm.aarch64.sve.whilewr.b.nx16i1",
        "llvm.aarch64.sve.whilewr.b",
    ),
    (
        "llvm.aarch64.sve.whilewr.d.nx2i1",
        "llvm.aarch64.sve.whilewr.d",
    ),
    (
        "llvm.aarch64.sve.whilewr.h.nx8i1",
        "llvm.aarch64.sve.whilewr.h",
    ),
    (
        "llvm.aarch64.sve.whilewr.s.nx4i1",
        "llvm.aarch64.sve.whilewr.s",
    ),
    ("llvm.aarch64.thread.pointer", "llvm.thread.pointer"),
    ("llvm.abs.2xi64", "llvm.abs"),
    ("llvm.amdgcn.alignbit", "llvm.fshr"),
    (
        "llvm.amdgcn.image.load.1d.f32i32",
        "llvm.amdgcn.image.load.1d",
    ),
    (
        "llvm.amdgcn.image.load.1d.v2f32i32",
        "llvm.amdgcn.image.load.1d",
    ),
    (
        "llvm.amdgcn.image.load.1d.v4f32i32",
        "llvm.amdgcn.image.load.1d",
    ),
    (
        "llvm.amdgcn.image.load.1darray.v4f32i32",
        "llvm.amdgcn.image.load.1darray",
    ),
    (
        "llvm.amdgcn.image.load.2d.v4f32i32",
        "llvm.amdgcn.image.load.2d",
    ),
    (
        "llvm.amdgcn.image.load.2darray.v4f32i32",
        "llvm.amdgcn.image.load.2darray",
    ),
    (
        "llvm.amdgcn.image.load.2darraymsaa.v4f32i32",
        "llvm.amdgcn.image.load.2darraymsaa",
    ),
    (
        "llvm.amdgcn.image.load.2dmsaa.v4f32i32",
        "llvm.amdgcn.image.load.2dmsaa",
    ),
    (
        "llvm.amdgcn.image.load.3d.v4f32i32",
        "llvm.amdgcn.image.load.3d",
    ),
    (
        "llvm.amdgcn.image.load.cube.v4f32i32",
        "llvm.amdgcn.image.load.cube",
    ),
    (
        "llvm.amdgcn.image.load.mip.1d.v4f32i32",
        "llvm.amdgcn.image.load.mip.1d",
    ),
    (
        "llvm.amdgcn.image.load.mip.2d.f32i32",
        "llvm.amdgcn.image.load.mip.2d",
    ),
    (
        "llvm.amdgcn.image.load.mip.2d.v2f32i32",
        "llvm.amdgcn.image.load.mip.2d",
    ),
    (
        "llvm.amdgcn.image.load.mip.2d.v4f32i32",
        "llvm.amdgcn.image.load.mip.2d",
    ),
    (
        "llvm.amdgcn.image.msaa.load.2darraymsaa.v4f16i32",
        "llvm.amdgcn.image.msaa.load.2darraymsaa",
    ),
    (
        "llvm.amdgcn.image.msaa.load.2darraymsaa.v4f32i32",
        "llvm.amdgcn.image.msaa.load.2darraymsaa",
    ),
    (
        "llvm.amdgcn.image.msaa.load.2dmsaa.v4f16i32",
        "llvm.amdgcn.image.msaa.load.2dmsaa",
    ),
    (
        "llvm.amdgcn.image.msaa.load.2dmsaa.v4f32i32",
        "llvm.amdgcn.image.msaa.load.2dmsaa",
    ),
    (
        "llvm.amdgcn.image.msaa.load.x.2darraymsaa.v4f32i32",
        "llvm.amdgcn.image.msaa.load.x.2darraymsaa",
    ),
    (
        "llvm.amdgcn.image.msaa.load.x.2dmsaa.v2f32i32",
        "llvm.amdgcn.image.msaa.load.x.2dmsaa",
    ),
    (
        "llvm.amdgcn.image.msaa.load.x.2dmsaa.v4f32i32",
        "llvm.amdgcn.image.msaa.load.x.2dmsaa",
    ),
    (
        "llvm.amdgcn.image.sample.1d.v4f32i32",
        "llvm.amdgcn.image.sample.1d",
    ),
    (
        "llvm.amdgcn.image.sample.2d.f16i32",
        "llvm.amdgcn.image.sample.2d",
    ),
    (
        "llvm.amdgcn.image.sample.2d.v2f16i32",
        "llvm.amdgcn.image.sample.2d",
    ),
    (
        "llvm.amdgcn.image.sample.b.2d.v3f16i32",
        "llvm.amdgcn.image.sample.b.2d",
    ),
    (
        "llvm.amdgcn.image.sample.b.2d.v4f16i32",
        "llvm.amdgcn.image.sample.b.2d",
    ),
    (
        "llvm.amdgcn.image.sample.c.d.1d.v2f16i32",
        "llvm.amdgcn.image.sample.c.d.1d",
    ),
    (
        "llvm.amdgcn.image.sample.c.d.o.2darray.f32i32",
        "llvm.amdgcn.image.sample.c.d.o.2darray",
    ),
    (
        "llvm.amdgcn.image.sample.c.d.o.2darray.v2f32i32",
        "llvm.amdgcn.image.sample.c.d.o.2darray",
    ),
    (
        "llvm.amdgcn.image.sample.d.1d.f32.nortn",
        "llvm.amdgcn.image.sample.d.1d",
    ),
    (
        "llvm.amdgcn.image.sample.d.2d.f32.nortn",
        "llvm.amdgcn.image.sample.d.2d",
    ),
    ("llvm.amdgcn.ldexp", "llvm.ldexp"),
    ("llvm.amdgcn.s.buffer.load.u16", "llvm.amdgcn.s.buffer.load"),
    ("llvm.amdgcn.s.buffer.load.u8", "llvm.amdgcn.s.buffer.load"),
    (
        "llvm.amdgcn.swmmac.f16.16x16x32.f16.v8f16.v8f16.v16f16.",
        "llvm.amdgcn.swmmac.f16.16x16x32",
    ),
    (
        "llvm.amdgcn.wmma.f16.16x16x16.f16.b8f16",
        "llvm.amdgcn.wmma.f16.16x16x16",
    ),
    ("llvm.arm.ldaex.p0i32", "llvm.arm.ldaex"),
    ("llvm.arm.ldrex.p0i32", "llvm.arm.ldrex"),
    ("llvm.arm.mve.vrintn", "llvm.roundeven"),
    ("llvm.arm.neon.vclz", "llvm.ctlz"),
    ("llvm.arm.neon.vcnt", "llvm.ctpop"),
    ("llvm.arm.neon.vqadds", "llvm.sadd.sat"),
    ("llvm.arm.neon.vqaddu", "llvm.uadd.sat"),
    ("llvm.arm.neon.vqsubs", "llvm.ssub.sat"),
    ("llvm.arm.neon.vqsubu", "llvm.usub.sat"),
    ("llvm.arm.neon.vrinta", "llvm.round"),
    ("llvm.arm.neon.vrintm", "llvm.floor"),
    ("llvm.arm.neon.vrintn", "llvm.roundeven"),
    ("llvm.arm.neon.vrintp", "llvm.ceil"),
    ("llvm.arm.neon.vrintx", "llvm.rint"),
    ("llvm.arm.neon.vrintz", "llvm.trunc"),
    ("llvm.arm.rbit", "llvm.bitreverse"),
    ("llvm.arm.stlex.p0i32", "llvm.arm.stlex"),
    ("llvm.arm.strex.p0i32", "llvm.arm.strex"),
    ("llvm.arm.thread.pointer", "llvm.thread.pointer"),
    (
        "llvm.bpf.preserve.field.info.p0.s1s",
        "llvm.bpf.preserve.field.info",
    ),
    (
        "llvm.bpf.preserve.field.info.p0.ts",
        "llvm.bpf.preserve.field.info",
    ),
    (
        "llvm.coro.suspend.async.sl_p0i8p0s_swift.error.4.220.413.429.445.461.672.683ss",
        "llvm.coro.suspend.async",
    ),
    (
        "llvm.coro.suspend.async.sl_p0i8p0s_swift.errorss",
        "llvm.coro.suspend.async",
    ),
    (
        "llvm.coro.suspend.retcon.i1p0p0i8",
        "llvm.coro.suspend.retcon",
    ),
    ("llvm.ctpop.2xi32", "llvm.ctpop"),
    ("llvm.ctpop.v1", "llvm.ctpop"),
    (
        "llvm.experimental.gc.relocate.beefdead",
        "llvm.experimental.gc.relocate",
    ),
    (
        "llvm.experimental.gc.relocate.p1.test",
        "llvm.experimental.gc.relocate",
    ),
    (
        "llvm.experimental.gc.relocate.p1.tests",
        "llvm.experimental.gc.relocate",
    ),
    (
        "llvm.experimental.gc.relocate.p1i32",
        "llvm.experimental.gc.relocate",
    ),
    (
        "llvm.experimental.gc.statepoint.deadbeef",
        "llvm.experimental.gc.statepoint",
    ),
    ("llvm.experimental.stepvector", "llvm.stepvector"),
    (
        "llvm.experimental.vector.deinterleave2",
        "llvm.vector.deinterleave2",
    ),
    ("llvm.experimental.vector.extract", "llvm.vector.extract"),
    ("llvm.experimental.vector.insert", "llvm.vector.insert"),
    (
        "llvm.experimental.vector.interleave2",
        "llvm.vector.interleave2",
    ),
    (
        "llvm.experimental.vector.reduce.add",
        "llvm.vector.reduce.add",
    ),
    (
        "llvm.experimental.vector.reduce.and",
        "llvm.vector.reduce.and",
    ),
    (
        "llvm.experimental.vector.reduce.fmax",
        "llvm.vector.reduce.fmax",
    ),
    (
        "llvm.experimental.vector.reduce.fmin",
        "llvm.vector.reduce.fmin",
    ),
    (
        "llvm.experimental.vector.reduce.or",
        "llvm.vector.reduce.or",
    ),
    (
        "llvm.experimental.vector.reduce.smax",
        "llvm.vector.reduce.smax",
    ),
    (
        "llvm.experimental.vector.reduce.smin",
        "llvm.vector.reduce.smin",
    ),
    (
        "llvm.experimental.vector.reduce.umax",
        "llvm.vector.reduce.umax",
    ),
    (
        "llvm.experimental.vector.reduce.umin",
        "llvm.vector.reduce.umin",
    ),
    (
        "llvm.experimental.vector.reduce.v2.fadd",
        "llvm.vector.reduce.fadd",
    ),
    (
        "llvm.experimental.vector.reduce.v2.fmul",
        "llvm.vector.reduce.fmul",
    ),
    (
        "llvm.experimental.vector.reduce.xor",
        "llvm.vector.reduce.xor",
    ),
    ("llvm.experimental.vector.reverse", "llvm.vector.reverse"),
    ("llvm.experimental.vector.splice", "llvm.vector.splice"),
    ("llvm.fabs.nx2f32", "llvm.fabs"),
    ("llvm.fabs.nx2f64", "llvm.fabs"),
    ("llvm.fabs.nx4f32", "llvm.fabs"),
    (
        "llvm.hexagon.V6.pred.typecast.128B.s1",
        "llvm.hexagon.V6.pred.typecast.128B",
    ),
    (
        "llvm.hexagon.V6.pred.typecast.128B.s2",
        "llvm.hexagon.V6.pred.typecast.128B",
    ),
    ("llvm.invariant.end.p3i8", "llvm.invariant.end"),
    ("llvm.invariant.end.unnamed", "llvm.invariant.end"),
    (
        "llvm.invariant.group.barrier",
        "llvm.launder.invariant.group",
    ),
    ("llvm.invariant.start.p3i8", "llvm.invariant.start"),
    ("llvm.invariant.start.unnamed", "llvm.invariant.start"),
    ("llvm.lifetime.end.p0i8", "llvm.lifetime.end"),
    ("llvm.lifetime.end.unnamed", "llvm.lifetime.end"),
    ("llvm.lifetime.start.p0i8", "llvm.lifetime.start"),
    ("llvm.lifetime.start.unnamed", "llvm.lifetime.start"),
    ("llvm.masked.load.v4f32.p", "llvm.masked.load"),
    ("llvm.masked.load.v4i32.p", "llvm.masked.load"),
    ("llvm.masked.load.v64f16.p0v64f16", "llvm.masked.load"),
    ("llvm.masked.load.v8i32.p", "llvm.masked.load"),
    ("llvm.masked.store.v4i32.p", "llvm.masked.store"),
    (
        "llvm.matrix.column.major.store.v4i32.vi32",
        "llvm.matrix.column.major.store",
    ),
    ("llvm.maximum.nx2f32", "llvm.maximum"),
    ("llvm.maximum.nx2f64", "llvm.maximum"),
    ("llvm.maximum.nx4f32", "llvm.maximum"),
    ("llvm.maxnum.nx2f32", "llvm.maxnum"),
    ("llvm.maxnum.nx2f64", "llvm.maxnum"),
    ("llvm.maxnum.nx4f32", "llvm.maxnum"),
    ("llvm.memcpy.p0i8.p0i8", "llvm.memcpy"),
    ("llvm.memcpy.p0i8.p2i8", "llvm.memcpy"),
    ("llvm.memcpy.p4i8.p0i8", "llvm.memcpy"),
    ("llvm.memset.p0.rtx_def", "llvm.memset"),
    ("llvm.memset.p0i8", "llvm.memset"),
    ("llvm.memset.p1i8", "llvm.memset"),
    ("llvm.memset.p3i8", "llvm.memset"),
    ("llvm.memset.p4i8", "llvm.memset"),
    ("llvm.minimum.nx2f32", "llvm.minimum"),
    ("llvm.minimum.nx2f64", "llvm.minimum"),
    ("llvm.minimum.nx4f32", "llvm.minimum"),
    ("llvm.minnum.nx2f32", "llvm.minnum"),
    ("llvm.minnum.nx2f64", "llvm.minnum"),
    ("llvm.minnum.nx4f32", "llvm.minnum"),
    ("llvm.nvvm.brev32", "llvm.bitreverse"),
    ("llvm.nvvm.brev64", "llvm.bitreverse"),
    ("llvm.nvvm.clz.i", "llvm.ctlz"),
    ("llvm.nvvm.popc.i", "llvm.ctpop"),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.col.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.col.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.col.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.col.stride.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.col.stride.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.col.stride.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.row.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.row.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.row.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.row.stride.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.row.stride.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.a.row.stride.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.a.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.col.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.col.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.col.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.col.stride.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.col.stride.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.col.stride.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.row.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.row.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.row.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.row.stride.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.row.stride.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.b.row.stride.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.b.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.f32.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.f32.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.f32.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride.f32.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride.f32.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride.f32.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.col.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.f32.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.f32.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.f32.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride.f16.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride.f16.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride.f16.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride.f32.p0i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride.f32.p1i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride",
    ),
    (
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride.f32.p3i8",
        "llvm.nvvm.wmma.m16n16k16.load.c.row.stride",
    ),
    ("llvm.objectsize.i32.unnamed", "llvm.objectsize"),
    ("llvm.objectsize.i64.p0i8", "llvm.objectsize"),
    ("llvm.prefetch.pf", "llvm.prefetch"),
    ("llvm.prefetch.unnamed", "llvm.prefetch"),
    (
        "llvm.preserve.array.access.index.p0.anons.p0.anons",
        "llvm.preserve.array.access.index",
    ),
    (
        "llvm.preserve.array.access.index.p0.net_devices.p0.net_devices",
        "llvm.preserve.array.access.index",
    ),
    (
        "llvm.preserve.array.access.index.p0.s1s.p0.s1s",
        "llvm.preserve.array.access.index",
    ),
    (
        "llvm.preserve.array.access.index.p0.ss.p0.ss",
        "llvm.preserve.array.access.index",
    ),
    (
        "llvm.preserve.array.access.index.p0.ts.p0.ts",
        "llvm.preserve.array.access.index",
    ),
    (
        "llvm.preserve.array.access.index.p0.us.p0.us",
        "llvm.preserve.array.access.index",
    ),
    (
        "llvm.preserve.array.access.index.p0.v3s.p0.v3s",
        "llvm.preserve.array.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.anons.p0.anons",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.anons.p0.sk_buffs",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.net_devices.p0.sk_buffs",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.__ss",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.__ts",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.anons",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.bs",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.info_ts",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.net_devices",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.s1s",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.ss",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.t1s",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.ts",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.tts",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.u1s",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.v1s",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.p0.v3s",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.s1s.p0.r1s",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.t1s.p0.s1s",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.struct.access.index.p0.v2s.p0.v3s",
        "llvm.preserve.struct.access.index",
    ),
    (
        "llvm.preserve.union.access.index.p0.__ss.p0.__ss",
        "llvm.preserve.union.access.index",
    ),
    (
        "llvm.preserve.union.access.index.p0.__ts.p0.__ts",
        "llvm.preserve.union.access.index",
    ),
    (
        "llvm.preserve.union.access.index.p0.anons.p0.anons",
        "llvm.preserve.union.access.index",
    ),
    (
        "llvm.preserve.union.access.index.p0.sk_buffs.p0.sk_buffs",
        "llvm.preserve.union.access.index",
    ),
    (
        "llvm.preserve.union.access.index.p0.u1s.p0.u1s",
        "llvm.preserve.union.access.index",
    ),
    (
        "llvm.preserve.union.access.index.p0.us.p0.us",
        "llvm.preserve.union.access.index",
    ),
    ("llvm.ptr.annotation.p0i16", "llvm.ptr.annotation"),
    ("llvm.ptr.annotation.p0i256", "llvm.ptr.annotation"),
    ("llvm.ptr.annotation.p0i8", "llvm.ptr.annotation"),
    ("llvm.ptrmask.p0.p0.struct", "llvm.ptrmask"),
    (
        "llvm.riscv.tuple.extract.v16f16.triscv.vector.tuple_nxv32i8_2t",
        "llvm.riscv.tuple.extract.nxv16f16.triscv.vector.tuple_nxv32i8_2t",
    ),
    (
        "llvm.riscv.vloxseg2",
        "llvm.riscv.vloxseg2.triscv.vector.tuple_nxv32i8_2t",
    ),
    (
        "llvm.riscv.vlseg2.mask",
        "llvm.riscv.vlseg2.mask.triscv.vector.tuple_nxv32i8_2t",
    ),
    (
        "llvm.riscv.vsseg4",
        "llvm.riscv.vsseg4.triscv.vector.tuple_nxv16i8_4t",
    ),
    ("llvm.uadd.sat.2xi8", "llvm.uadd.sat"),
    ("llvm.vector.extract.v4i32.nxv1132", "llvm.vector.extract"),
    ("llvm.vector.insert.nxv6f64.nx2f64", "llvm.vector.insert"),
    ("llvm.vector.insert.nxv8f64.nx2f64", "llvm.vector.insert"),
    ("llvm.vector.reduce.fadd.v4f8", "llvm.vector.reduce.fadd"),
    ("llvm.vp.load.nxv2f32.p0nxv2f32", "llvm.vp.load"),
    ("llvm.vp.store.nxv2f32.p0nxv2f32", "llvm.vp.store"),
    ("llvm.vp.trunc.nxv1i8.nxvi16", "llvm.vp.trunc"),
    ("llvm.vp.zext.nxvi64", "llvm.vp.zext"),
    (
        "llvm.wasm.dot.i8x16.i7x16.add.signed",
        "llvm.wasm.relaxed.dot.i8x16.i7x16.add.signed",
    ),
    (
        "llvm.wasm.dot.i8x16.i7x16.signed",
        "llvm.wasm.relaxed.dot.i8x16.i7x16.signed",
    ),
    ("llvm.wasm.fma", "llvm.wasm.relaxed.madd"),
    ("llvm.wasm.fms", "llvm.wasm.relaxed.nmadd"),
    ("llvm.wasm.laneselect", "llvm.wasm.relaxed.laneselect"),
    ("llvm.x86.seh.recoverfp", "llvm.eh.recoverfp"),
];
