//! What LangRef says each intrinsic takes.
//!
//! Generated by `corpus/intrinsic-signatures.nu`, which explains the
//! derivation and what it leaves out. In short: LangRef documents an
//! overloaded intrinsic with one `declare` line per instantiation, so a
//! position whose type is the same in all of them is a rule and a position
//! whose type varies is not. Only the arity and the types that are the same
//! everywhere are here, which is a smaller claim than upstream makes.

/// What one argument position has to be.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Parameter {
    /// Overloaded, or a type this table does not try to match.
    Any,
    Int(u32),
    Pointer,
    Metadata,
    Float,
}

/// The signature documented under exactly this name, with no reduction.
pub fn signature_exact(name: &str) -> Option<&'static [Parameter]> {
    let index = SIGNATURES
        .binary_search_by_key(&name, |(name, _)| *name)
        .ok()?;
    Some(SIGNATURES[index].1)
}

/// The signature LangRef documents for this name or for the one it
/// instantiates, or `None` when it documents none or documents inconsistent
/// arities.
///
/// The reduction is `super::candidates`, which drops trailing mangled types
/// and stops at the first component that is a word, so a name cannot reach a
/// shorter one that is merely a prefix of it.
pub fn signature(name: &str) -> Option<&'static [Parameter]> {
    super::candidates(name).find_map(signature_exact)
}

/// Sorted, so the lookup can be a binary search.
static SIGNATURES: &[(&str, &[Parameter])] = &[
    ("llvm.abs", &[Parameter::Any, Parameter::Int(1)]),
    ("llvm.acos", &[Parameter::Any]),
    ("llvm.addressofreturnaddress", &[]),
    ("llvm.adjust.trampoline", &[Parameter::Pointer]),
    ("llvm.allow.runtime.check", &[Parameter::Metadata]),
    ("llvm.allow.ubsan.check", &[Parameter::Int(8)]),
    (
        "llvm.annotation",
        &[
            Parameter::Any,
            Parameter::Pointer,
            Parameter::Pointer,
            Parameter::Int(32),
        ],
    ),
    ("llvm.asin", &[Parameter::Any]),
    ("llvm.assume", &[Parameter::Int(1)]),
    ("llvm.atan", &[Parameter::Any]),
    ("llvm.atan2", &[Parameter::Any, Parameter::Any]),
    ("llvm.bitreverse", &[Parameter::Any]),
    ("llvm.bswap", &[Parameter::Any]),
    (
        "llvm.call.preallocated.arg",
        &[Parameter::Any, Parameter::Int(32)],
    ),
    ("llvm.call.preallocated.setup", &[Parameter::Int(32)]),
    ("llvm.call.preallocated.teardown", &[Parameter::Any]),
    ("llvm.canonicalize", &[Parameter::Any]),
    ("llvm.ceil", &[Parameter::Any]),
    (
        "llvm.clear_cache",
        &[Parameter::Pointer, Parameter::Pointer],
    ),
    ("llvm.codeview.annotation", &[Parameter::Metadata]),
    ("llvm.convert.from.fp16", &[Parameter::Int(16)]),
    ("llvm.convert.to.fp16", &[Parameter::Any]),
    ("llvm.copysign", &[Parameter::Any, Parameter::Any]),
    ("llvm.cos", &[Parameter::Any]),
    ("llvm.cosh", &[Parameter::Any]),
    ("llvm.ctlz", &[Parameter::Any, Parameter::Int(1)]),
    ("llvm.ctpop", &[Parameter::Any]),
    ("llvm.cttz", &[Parameter::Any, Parameter::Int(1)]),
    ("llvm.donothing", &[Parameter::Any]),
    ("llvm.exp", &[Parameter::Any]),
    ("llvm.exp10", &[Parameter::Any]),
    ("llvm.exp2", &[Parameter::Any]),
    ("llvm.expect", &[Parameter::Any, Parameter::Any]),
    (
        "llvm.expect.with.probability",
        &[Parameter::Any, Parameter::Any, Parameter::Float],
    ),
    (
        "llvm.experimental.cttz.elts",
        &[Parameter::Any, Parameter::Int(1)],
    ),
    (
        "llvm.experimental.get.vector.length",
        &[Parameter::Any, Parameter::Int(32), Parameter::Int(1)],
    ),
    ("llvm.experimental.noalias.scope.decl", &[Parameter::Any]),
    (
        "llvm.experimental.vector.compress",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.experimental.vector.extract.last.active",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.experimental.vector.histogram.add",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.experimental.vector.histogram.uadd.sat",
        &[Parameter::Any, Parameter::Int(32), Parameter::Any],
    ),
    (
        "llvm.experimental.vector.histogram.umax",
        &[Parameter::Any, Parameter::Int(32), Parameter::Any],
    ),
    (
        "llvm.experimental.vector.histogram.umin",
        &[Parameter::Any, Parameter::Int(32), Parameter::Any],
    ),
    (
        "llvm.experimental.vector.match",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.experimental.vector.partial.reduce.add",
        &[Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.experimental.vp.reverse",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.experimental.vp.splat",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.experimental.vp.splice",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
            Parameter::Any,
            Parameter::Int(32),
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.experimental.vp.strided.load",
        &[
            Parameter::Pointer,
            Parameter::Int(64),
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.experimental.vp.strided.store",
        &[
            Parameter::Any,
            Parameter::Pointer,
            Parameter::Int(64),
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    ("llvm.experimental.widenable.condition", &[]),
    ("llvm.fabs", &[Parameter::Any]),
    ("llvm.floor", &[Parameter::Any]),
    (
        "llvm.fma",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.fmuladd",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    ("llvm.fptosi.sat", &[Parameter::Any]),
    ("llvm.fptoui.sat", &[Parameter::Any]),
    ("llvm.frameaddress", &[Parameter::Int(32)]),
    ("llvm.frexp", &[Parameter::Any]),
    (
        "llvm.fshl",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.fshr",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    ("llvm.gcread", &[Parameter::Pointer, Parameter::Pointer]),
    ("llvm.gcroot", &[Parameter::Pointer, Parameter::Pointer]),
    (
        "llvm.gcwrite",
        &[Parameter::Pointer, Parameter::Pointer, Parameter::Pointer],
    ),
    (
        "llvm.get.active.lane.mask",
        &[Parameter::Any, Parameter::Any],
    ),
    ("llvm.get.dynamic.area.offset", &[]),
    ("llvm.get.fpenv", &[]),
    ("llvm.get.fpmode", &[]),
    ("llvm.get.rounding", &[]),
    (
        "llvm.init.trampoline",
        &[Parameter::Pointer, Parameter::Pointer, Parameter::Pointer],
    ),
    (
        "llvm.invariant.end",
        &[Parameter::Pointer, Parameter::Int(64), Parameter::Any],
    ),
    (
        "llvm.invariant.start",
        &[Parameter::Int(64), Parameter::Any],
    ),
    ("llvm.is.constant", &[Parameter::Any]),
    ("llvm.is.constant.TYPENAME", &[Parameter::Any]),
    ("llvm.is.fpclass", &[Parameter::Any, Parameter::Int(32)]),
    ("llvm.launder.invariant.group", &[Parameter::Pointer]),
    ("llvm.ldexp", &[Parameter::Any, Parameter::Any]),
    ("llvm.lifetime.end", &[Parameter::Int(64), Parameter::Any]),
    ("llvm.lifetime.start", &[Parameter::Int(64), Parameter::Any]),
    ("llvm.llrint", &[Parameter::Any]),
    ("llvm.llround", &[Parameter::Any]),
    (
        "llvm.load.relative.iN",
        &[Parameter::Pointer, Parameter::Any],
    ),
    (
        "llvm.localrecover",
        &[Parameter::Pointer, Parameter::Pointer, Parameter::Int(32)],
    ),
    ("llvm.log", &[Parameter::Any]),
    ("llvm.log10", &[Parameter::Any]),
    ("llvm.log2", &[Parameter::Any]),
    ("llvm.loop.decrement", &[Parameter::Any]),
    ("llvm.loop.decrement.reg", &[Parameter::Any, Parameter::Any]),
    ("llvm.lrint", &[Parameter::Any]),
    ("llvm.lround", &[Parameter::Any]),
    (
        "llvm.masked.compressstore",
        &[Parameter::Any, Parameter::Pointer, Parameter::Any],
    ),
    (
        "llvm.masked.expandload",
        &[Parameter::Pointer, Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.masked.gather",
        &[
            Parameter::Any,
            Parameter::Int(32),
            Parameter::Any,
            Parameter::Any,
        ],
    ),
    (
        "llvm.masked.load",
        &[
            Parameter::Pointer,
            Parameter::Int(32),
            Parameter::Any,
            Parameter::Any,
        ],
    ),
    (
        "llvm.masked.scatter",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
            Parameter::Any,
        ],
    ),
    (
        "llvm.masked.store",
        &[
            Parameter::Any,
            Parameter::Pointer,
            Parameter::Int(32),
            Parameter::Any,
        ],
    ),
    ("llvm.maximum", &[Parameter::Any, Parameter::Any]),
    ("llvm.maximumnum", &[Parameter::Any, Parameter::Any]),
    ("llvm.maxnum", &[Parameter::Any, Parameter::Any]),
    ("llvm.minimum", &[Parameter::Any, Parameter::Any]),
    ("llvm.minimumnum", &[Parameter::Any, Parameter::Any]),
    ("llvm.minnum", &[Parameter::Any, Parameter::Any]),
    ("llvm.modf", &[Parameter::Any]),
    ("llvm.nearbyint", &[Parameter::Any]),
    ("llvm.objc.autorelease", &[Parameter::Pointer]),
    ("llvm.objc.autoreleasePoolPop", &[Parameter::Pointer]),
    ("llvm.objc.autoreleasePoolPush", &[]),
    ("llvm.objc.autoreleaseReturnValue", &[Parameter::Pointer]),
    (
        "llvm.objc.copyWeak",
        &[Parameter::Pointer, Parameter::Pointer],
    ),
    ("llvm.objc.destroyWeak", &[Parameter::Pointer]),
    (
        "llvm.objc.initWeak",
        &[Parameter::Pointer, Parameter::Pointer],
    ),
    ("llvm.objc.loadWeak", &[Parameter::Pointer]),
    ("llvm.objc.loadWeakRetained", &[Parameter::Pointer]),
    (
        "llvm.objc.moveWeak",
        &[Parameter::Pointer, Parameter::Pointer],
    ),
    ("llvm.objc.release", &[Parameter::Pointer]),
    ("llvm.objc.retain", &[Parameter::Pointer]),
    ("llvm.objc.retainAutorelease", &[Parameter::Pointer]),
    (
        "llvm.objc.retainAutoreleaseReturnValue",
        &[Parameter::Pointer],
    ),
    (
        "llvm.objc.retainAutoreleasedReturnValue",
        &[Parameter::Pointer],
    ),
    ("llvm.objc.retainBlock", &[Parameter::Pointer]),
    (
        "llvm.objc.storeStrong",
        &[Parameter::Pointer, Parameter::Pointer],
    ),
    (
        "llvm.objc.storeWeak",
        &[Parameter::Pointer, Parameter::Pointer],
    ),
    (
        "llvm.objectsize",
        &[
            Parameter::Pointer,
            Parameter::Int(1),
            Parameter::Int(1),
            Parameter::Int(1),
        ],
    ),
    ("llvm.pcmarker", &[Parameter::Int(32)]),
    ("llvm.pow", &[Parameter::Any, Parameter::Any]),
    ("llvm.powi", &[Parameter::Any, Parameter::Any]),
    (
        "llvm.prefetch",
        &[
            Parameter::Pointer,
            Parameter::Int(32),
            Parameter::Int(32),
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.ptr.annotation",
        &[
            Parameter::Any,
            Parameter::Pointer,
            Parameter::Pointer,
            Parameter::Int(32),
        ],
    ),
    ("llvm.read_register", &[Parameter::Metadata]),
    ("llvm.read_volatile_register", &[Parameter::Metadata]),
    ("llvm.readcyclecounter", &[]),
    ("llvm.readsteadycounter", &[]),
    ("llvm.reset.fpenv", &[]),
    ("llvm.reset.fpmode", &[]),
    ("llvm.returnaddress", &[Parameter::Int(32)]),
    ("llvm.rint", &[Parameter::Any]),
    ("llvm.round", &[Parameter::Any]),
    ("llvm.roundeven", &[Parameter::Any]),
    ("llvm.sadd.sat", &[Parameter::Any, Parameter::Any]),
    ("llvm.sadd.with.overflow", &[Parameter::Any, Parameter::Any]),
    ("llvm.scmp", &[Parameter::Any, Parameter::Any]),
    (
        "llvm.sdiv.fix",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.sdiv.fix.sat",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    ("llvm.seh.scope.begin", &[]),
    ("llvm.seh.scope.end", &[]),
    ("llvm.seh.try.begin", &[]),
    ("llvm.seh.try.end", &[]),
    ("llvm.set.fpenv", &[Parameter::Any]),
    ("llvm.set.fpmode", &[Parameter::Any]),
    ("llvm.set.loop.iterations", &[Parameter::Any]),
    ("llvm.set.rounding", &[Parameter::Int(32)]),
    ("llvm.sin", &[Parameter::Any]),
    ("llvm.sincos", &[Parameter::Any]),
    ("llvm.sincospi", &[Parameter::Any]),
    ("llvm.sinh", &[Parameter::Any]),
    ("llvm.smax", &[Parameter::Any, Parameter::Any]),
    ("llvm.smin", &[Parameter::Any, Parameter::Any]),
    (
        "llvm.smul.fix",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.smul.fix.sat",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    ("llvm.smul.with.overflow", &[Parameter::Any, Parameter::Any]),
    ("llvm.sponentry", &[]),
    ("llvm.sqrt", &[Parameter::Any]),
    ("llvm.ssa.copy", &[Parameter::Any]),
    ("llvm.sshl.sat", &[Parameter::Any, Parameter::Any]),
    ("llvm.ssub.sat", &[Parameter::Any, Parameter::Any]),
    ("llvm.ssub.with.overflow", &[Parameter::Any, Parameter::Any]),
    ("llvm.stackguard", &[]),
    (
        "llvm.stackprotector",
        &[Parameter::Pointer, Parameter::Pointer],
    ),
    ("llvm.stackrestore", &[Parameter::Any]),
    ("llvm.stacksave", &[]),
    ("llvm.start.loop.iterations", &[Parameter::Any]),
    ("llvm.stepvector", &[]),
    ("llvm.strip.invariant.group", &[Parameter::Pointer]),
    ("llvm.swift.async.context.addr", &[]),
    ("llvm.tan", &[Parameter::Any]),
    ("llvm.tanh", &[Parameter::Any]),
    ("llvm.test.set.loop.iterations", &[Parameter::Any]),
    ("llvm.test.start.loop.iterations", &[Parameter::Any]),
    ("llvm.thread.pointer", &[]),
    ("llvm.threadlocal.address", &[Parameter::Any]),
    ("llvm.trunc", &[Parameter::Any]),
    (
        "llvm.type.checked.load",
        &[Parameter::Pointer, Parameter::Int(32), Parameter::Any],
    ),
    (
        "llvm.type.checked.load.relative",
        &[Parameter::Pointer, Parameter::Int(32), Parameter::Any],
    ),
    ("llvm.type.test", &[Parameter::Pointer, Parameter::Any]),
    ("llvm.uadd.sat", &[Parameter::Any, Parameter::Any]),
    ("llvm.uadd.with.overflow", &[Parameter::Any, Parameter::Any]),
    ("llvm.ucmp", &[Parameter::Any, Parameter::Any]),
    (
        "llvm.udiv.fix",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.udiv.fix.sat",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    ("llvm.umax", &[Parameter::Any, Parameter::Any]),
    ("llvm.umin", &[Parameter::Any, Parameter::Any]),
    (
        "llvm.umul.fix",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.umul.fix.sat",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    ("llvm.umul.with.overflow", &[Parameter::Any, Parameter::Any]),
    ("llvm.ushl.sat", &[Parameter::Any, Parameter::Any]),
    ("llvm.usub.sat", &[Parameter::Any, Parameter::Any]),
    ("llvm.usub.with.overflow", &[Parameter::Any, Parameter::Any]),
    ("llvm.va_copy", &[Parameter::Any, Parameter::Any]),
    ("llvm.va_end", &[Parameter::Any]),
    ("llvm.va_start", &[Parameter::Any]),
    (
        "llvm.var.annotation",
        &[
            Parameter::Pointer,
            Parameter::Pointer,
            Parameter::Pointer,
            Parameter::Int(32),
        ],
    ),
    ("llvm.vector.deinterleave2", &[Parameter::Any]),
    ("llvm.vector.deinterleave3", &[Parameter::Any]),
    ("llvm.vector.deinterleave5", &[Parameter::Any]),
    ("llvm.vector.deinterleave7", &[Parameter::Any]),
    ("llvm.vector.extract", &[Parameter::Any, Parameter::Int(64)]),
    (
        "llvm.vector.insert",
        &[Parameter::Any, Parameter::Any, Parameter::Int(64)],
    ),
    ("llvm.vector.interleave2", &[Parameter::Any, Parameter::Any]),
    (
        "llvm.vector.interleave3",
        &[Parameter::Any, Parameter::Any, Parameter::Any],
    ),
    (
        "llvm.vector.interleave5",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
        ],
    ),
    (
        "llvm.vector.interleave7",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
        ],
    ),
    ("llvm.vector.reduce.add", &[Parameter::Any]),
    ("llvm.vector.reduce.and", &[Parameter::Any]),
    ("llvm.vector.reduce.fadd", &[Parameter::Any, Parameter::Any]),
    ("llvm.vector.reduce.fmax", &[Parameter::Any]),
    ("llvm.vector.reduce.fmaximum", &[Parameter::Any]),
    ("llvm.vector.reduce.fmin", &[Parameter::Any]),
    ("llvm.vector.reduce.fminimum", &[Parameter::Any]),
    ("llvm.vector.reduce.fmul", &[Parameter::Any, Parameter::Any]),
    ("llvm.vector.reduce.mul", &[Parameter::Any]),
    ("llvm.vector.reduce.or", &[Parameter::Any]),
    ("llvm.vector.reduce.smax", &[Parameter::Any]),
    ("llvm.vector.reduce.smin", &[Parameter::Any]),
    ("llvm.vector.reduce.umax", &[Parameter::Any]),
    ("llvm.vector.reduce.umin", &[Parameter::Any]),
    ("llvm.vector.reduce.xor", &[Parameter::Any]),
    ("llvm.vector.reverse", &[Parameter::Any]),
    (
        "llvm.vector.splice",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.abs",
        &[
            Parameter::Any,
            Parameter::Int(1),
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.add",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.and",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.ashr",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.bitreverse",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.bswap",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.ceil",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.copysign",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.ctlz",
        &[
            Parameter::Any,
            Parameter::Int(1),
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.ctpop",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.cttz",
        &[
            Parameter::Any,
            Parameter::Int(1),
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.cttz.elts",
        &[
            Parameter::Any,
            Parameter::Int(1),
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fabs",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.fadd",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fcmp",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Metadata,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fdiv",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.floor",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.fma",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fmul",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fmuladd",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fneg",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.fpext",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.fptosi",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.fptoui",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.fptrunc",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.frem",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fshl",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fshr",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.fsub",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.gather",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.icmp",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Metadata,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.inttoptr",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.is.fpclass",
        &[
            Parameter::Any,
            Parameter::Int(32),
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.llrint",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.load",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.lrint",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.lshr",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.maximum",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.maxnum",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.merge",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.minimum",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.minnum",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.mul",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.nearbyint",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.or",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.ptrtoint",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.reduce.add",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.and",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.fadd",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.fmax",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.fmaximum",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.fmin",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.fminimum",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.fmul",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.mul",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.or",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.smax",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.smin",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.umax",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.umin",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.reduce.xor",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.rint",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.round",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.roundeven",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.roundtozero",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.scatter",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.sdiv",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.select",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.sext",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.shl",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.sitofp",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.smax",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.smin",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.sqrt",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.srem",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.store",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.sub",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.trunc",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.udiv",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.uitofp",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.vp.umax",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.umin",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.urem",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.xor",
        &[
            Parameter::Any,
            Parameter::Any,
            Parameter::Any,
            Parameter::Int(32),
        ],
    ),
    (
        "llvm.vp.zext",
        &[Parameter::Any, Parameter::Any, Parameter::Int(32)],
    ),
    (
        "llvm.write_register",
        &[Parameter::Metadata, Parameter::Any],
    ),
];
