//! What each target extension type is allowed to be.
//!
//! Generated by `corpus/target-extension-types.nu`; do not edit by hand.
//!
//! `target("name")` names a type the target defines, and upstream registers
//! each one with properties saying where it may appear. LangRef says the
//! properties exist and points at a C++ header for the list, so this is
//! measured against the assembler instead: each row is an answer it gave.
//!
//! A namespace carries defaults and a registered name may override them, so
//! the lookup asks for the name first and falls back to the namespace. A name
//! in neither table is one upstream does not know, and an unknown target
//! extension type has no properties at all: it has no size, so it cannot be
//! loaded, stored, allocated or held in a global.

/// Where a target extension type may appear.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub struct Properties {
    /// Whether the type has a size, which is what lets it be loaded and
    /// stored.
    pub sized: bool,
    /// Whether a global variable may have this type.
    pub global: bool,
    /// Whether `alloca` may name it.
    pub alloca: bool,
    /// Whether `zeroinitializer` is a value of it. `undef` and `poison` are
    /// values of every one of them and are not asked about.
    pub zeroinit: bool,
    /// Whether a vector may have it as an element. Most may not, which makes
    /// `<2 x target("spirv.Image")>` an invalid vector element type where
    /// `<2 x target("llvm.test.vectorelement")>` is a vector.
    pub vector: bool,
}

/// What a namespace gives every name in it that is not listed below.
static NAMESPACES: &[(&str, Properties)] = &[
    (
        "dx",
        Properties {
            sized: true,
            global: true,
            alloca: true,
            zeroinit: false,
            vector: false,
        },
    ),
    (
        "spirv",
        Properties {
            sized: true,
            global: true,
            alloca: true,
            zeroinit: true,
            vector: false,
        },
    ),
];

/// The names that differ from what their namespace would give them.
static NAMES: &[(&str, Properties)] = &[
    (
        "aarch64.svcount",
        Properties {
            sized: true,
            global: false,
            alloca: true,
            zeroinit: true,
            vector: false,
        },
    ),
    (
        "amdgcn.named.barrier",
        Properties {
            sized: true,
            global: true,
            alloca: false,
            zeroinit: false,
            vector: false,
        },
    ),
    (
        "llvm.test.vectorelement",
        Properties {
            sized: true,
            global: false,
            alloca: true,
            zeroinit: false,
            vector: true,
        },
    ),
    (
        "riscv.vector.tuple",
        Properties {
            sized: true,
            global: false,
            alloca: true,
            zeroinit: true,
            vector: false,
        },
    ),
    (
        "spirv.Image",
        Properties {
            sized: true,
            global: true,
            alloca: true,
            zeroinit: false,
            vector: false,
        },
    ),
    (
        "spirv.IntegralConstant",
        Properties {
            sized: false,
            global: false,
            alloca: false,
            zeroinit: false,
            vector: false,
        },
    ),
    (
        "spirv.Literal",
        Properties {
            sized: false,
            global: false,
            alloca: false,
            zeroinit: false,
            vector: false,
        },
    ),
    (
        "spirv.SignedImage",
        Properties {
            sized: true,
            global: true,
            alloca: true,
            zeroinit: false,
            vector: false,
        },
    ),
    (
        "spirv.Type",
        Properties {
            sized: true,
            global: true,
            alloca: true,
            zeroinit: false,
            vector: false,
        },
    ),
];

/// The properties of a target extension type, which are none at all for a
/// name upstream does not know.
pub fn properties(name: &str) -> Properties {
    if let Some((_, found)) = NAMES.iter().find(|(listed, _)| *listed == name) {
        return *found;
    }
    let Some((space, _)) = name.split_once('.') else {
        return Properties::default();
    };
    NAMESPACES
        .iter()
        .find(|(listed, _)| *listed == space)
        .map(|(_, found)| *found)
        .unwrap_or_default()
}
